# this is by far the shittiest markup format you can have. fuck this.

name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: fetch submodules
      run: git submodule update --init --recursive

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    #- name: Create Build Environment
    #  # Some projects don't allow in-source building, so create a separate build directory
    #  # We'll use this as our working directory for all subsequent commands
    #  #run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build .

    - name: Upload result
      uses: softprops/action-gh-release@v1
      with:
        files: Release/8bit-programmer.exe
        name: wintendo-${{ env.GITHUB_RUN_NUMBER }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
