# this is by far the shittiest markup format you can have. fuck this.

name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: fetch submodules
      run: git submodule update --init --recursive

    - name: msvc is shit
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: 14.0

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    #- name: Create Build Environment
    #  # Some projects don't allow in-source building, so create a separate build directory
    #  # We'll use this as our working directory for all subsequent commands
    #  #run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config Release

    - name: Package
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      shell: cmd
      env:
        GITHUB_RUN_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
      run: |
        @echo on
        mkdir 8bit-programmer
        move Release\8bit-programmer.exe 8bit-programmer\
        REM copy "%VCToolsRedistDir%\x64\Microsoft.VC142.CRT\vcruntime140.dll" 8bit-programmer
        REM copy "%VCToolsRedistDir%\x64\Microsoft.VC142.CRT\vcruntime140_1.dll" 8bit-programmer
        REM copy "%VCToolsRedistDir%\x64\Microsoft.VC142.CRT\MSVCP140.dll" 8bit-programmer
        REM copy "%VCToolsRedistDir%\x64\Microsoft.VC142.CRT\MSVCP140_1.dll" 8bit-programmer
        REM copy "%Qt5_Dir%\bin\Qt5Core.dll" 8bit-programmer
        REM copy "%Qt5_Dir%\bin\Qt5Gui.dll" 8bit-programmer
        REM copy "%Qt5_Dir%\bin\Qt5Widgets.dll" 8bit-programmer
        REM copy "%Qt5_Dir%\bin\Qt5SerialPort.dll" 8bit-programmer
        REM mkdir 8bit-programmer\platforms
        REM copy "%Qt5_Dir%\plugins\platforms\qwindows.dll" 8bit-programmer\platforms
        REM copy "README.md" 8bit-programmer
        cd 8bit-programmer
        windeployqt 8bit-programmer.exe
        cd ..
        7z a 8bit-programmer-v%GITHUB_RUN_NUMBER%.zip 8bit-programmer\*

    #cd /d "%VCINSTALLDIR%"
    #dir /s api-ms-win-crt-runtime-l1-1-0.dll
    #dir /s NETAPI32.dll
    #dir /s iphlpapi.dll
    #dir /s nsi.dll

    #cd /d "%WindowsSdkDir%"
    #dir /s api-ms-win-crt-runtime-l1-1-0.dll
    #dir /s NETAPI32.dll
    #dir /s iphlpapi.dll
    #dir /s nsi.dll


    - uses: ncipollo/release-action@v1
      with:
        artifacts: "8bit-programmer-*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 64
        allowUpdates: true
